# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: database.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61tabase.proto\x12\rredisDatabase\"4\n\x07Request\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x03val\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x06\n\x04_val\"\x18\n\x05Reply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xf3\x01\n\x0fredisOperations\x12\x35\n\x03get\x12\x16.redisDatabase.Request\x1a\x14.redisDatabase.Reply\"\x00\x12\x35\n\x03set\x12\x16.redisDatabase.Request\x1a\x14.redisDatabase.Reply\"\x00\x12\x38\n\x06\x65xists\x12\x16.redisDatabase.Request\x1a\x14.redisDatabase.Reply\"\x00\x12\x38\n\x06\x64\x65lete\x12\x16.redisDatabase.Request\x1a\x14.redisDatabase.Reply\"\x00\x62\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_REPLY = DESCRIPTOR.message_types_by_name['Reply']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'database_pb2'
  # @@protoc_insertion_point(class_scope:redisDatabase.Request)
  })
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'database_pb2'
  # @@protoc_insertion_point(class_scope:redisDatabase.Reply)
  })
_sym_db.RegisterMessage(Reply)

_REDISOPERATIONS = DESCRIPTOR.services_by_name['redisOperations']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=33
  _REQUEST._serialized_end=85
  _REPLY._serialized_start=87
  _REPLY._serialized_end=111
  _REDISOPERATIONS._serialized_start=114
  _REDISOPERATIONS._serialized_end=357
# @@protoc_insertion_point(module_scope)
